version: '3.0'

services:
  server:
    container_name: server
    image: aananko/nodejs2023q2-service-server
    build: .
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    depends_on:
      - postgres
    env_file: .env.docker
    networks:
      - server-network  
    restart: always 
    volumes:
      - ./src:/app/src
      - logs:/app/logs
  postgres:
    container_name: postgres
    image: aananko/nodejs2023q2-service-postgres
    build: ./src/database
    ports:
      - ${POSTGRES_PORT_DB_CONTAINER}:${POSTGRES_PORT}
    env_file: .env.docker
    networks:
      - server-network 
    restart: always 
    volumes:
      - pgdata:/var/lib/postgresql/data   
      - pglogs:/var/log/postgresql

networks:
  server-network:
    driver: bridge

volumes: 
  pgdata:
  pglogs:
  logs: