version: '3.0'

services:
  server:
    container_name: server
    build: .
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - server-network  
    restart: always 
    volumes:
      - ./src:/app/src 
  postgres:
    container_name: postgres
    build: ./src/database
    ports:
      - ${POSTGRES_PORT_DB_CONTAINER}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - server-network 
    restart: always    

networks:
  server-network:
    driver: bridge
